### ISSUE TITLE
Add '...' as preamble closing marker

### ISSUE THREAD

**Issue by crystalfp** [gojko/markdown-it-github-preamble#2]
The markdown files for Pandoc accept '...' as closing marker of the yaml preamble like this:
```
---
pagetitle: Persistent Identifiers
author: Myself 
lang: en
...

# Persistent Identifiers
Bla bla
```
Please add (or split) the marker parameter to beginMarker and endMarker for example.
Thanks!
mario

**Comment by gojko** [comment]
you can just provide an alternative symbol with options.marker

**Comment by crystalfp** [comment]
For what I understand of the code, you cannot open the preamble with `---` and close it with `...`

Maybe I misunderstood the `marker` option.

**Comment by gojko** [comment]
@crystalfp you're right, sorry I misread what you asked for; it's not possible to have different opening/closing markers now
